### ISSUE TITLE
Missing .whl file 

### ISSUE THREAD

**Issue by ShikaiWang-Sky** [CODA-Team/AnalogGym#1]
Hi guys, I tried to setup environment with docker; however, there seems missing a .whl file: torch-1.13.1+cpu-cp310-cp310-linux_x86_64.whl.

**Comment by ShikaiWang-Sky** [comment]
Also, I tried setup conda environment and run main_AMP.py, the error shows as following:

Register the environment
cpu
ERROR
Simulation errors, no .OP simulation results.
You need to run <_random_op_sims> to generate mean and std for transistor .OP parameters
Traceback (most recent call last):
  File ".../main_AMP.py", line 82, in <module>
    agent.train(num_steps)
  File ".../ddpg.py", line 220, in train
    state, info = self.env.reset() 
  File ".../gymnasium/wrappers/time_limit.py", line 75, in reset
    return self.env.reset(**kwargs)
  File ".../gymnasium/wrappers/order_enforcing.py", line 61, in reset
    return self.env.reset(**kwargs)
  File ".../gymnasium/wrappers/env_checker.py", line 57, in reset
    return env_reset_passive_checker(self.env, **kwargs)
  File ".../gymnasium/utils/passive_env_checker.py", line 186, in env_reset_passive_checker
    result = env.reset(**kwargs)
  File ".../AMP_NMCF.py", line 123, in reset
    observation = self._get_obs()
  File ".../AMP_NMCF.py", line 211, in _get_obs
    self.OP_M0 = self.op_results['M0']
TypeError: 'NoneType' object is not subscriptable

**Comment by krzhu** [comment]
Please shows your running steps and give a reproducible case

**Comment by Fican1** [comment]
> Also, I tried setup conda environment and run main_AMP.py, the error shows as following:
> 
> Register the environment cpu ERROR Simulation errors, no .OP simulation results. You need to run <_random_op_sims> to generate mean and std for transistor .OP parameters Traceback (most recent call last): File ".../main_AMP.py", line 82, in agent.train(num_steps) File ".../ddpg.py", line 220, in train state, info = self.env.reset() File ".../gymnasium/wrappers/time_limit.py", line 75, in reset return self.env.reset(**kwargs) File ".../gymnasium/wrappers/order_enforcing.py", line 61, in reset return self.env.reset(**kwargs) File ".../gymnasium/wrappers/env_checker.py", line 57, in reset return env_reset_passive_checker(self.env, **kwargs) File ".../gymnasium/utils/passive_env_checker.py", line 186, in env_reset_passive_checker result = env.reset(**kwargs) File ".../AMP_NMCF.py", line 123, in reset observation = self._get_obs() File ".../AMP_NMCF.py", line 211, in _get_obs self.OP_M0 = self.op_results['M0'] TypeError: 'NoneType' object is not subscriptable

To normalize the transistor attributes used in the observation matrix, you'll need the mean and standard deviation. 
These values can be obtained by running initial experiments with the class method `_init_random_sim`. 

For demonstration, we have already provided this data in the file `AMP_NMCF_op_mean_std.json`. 
When switching to a different circuit, you will need to generate this file yourself. 
To do so, simply set the parameter `'run_initial=True'` at the indicated location in [`main_AMP.py`](https://github.com/CODA-Team/AnalogGym/blob/main/RGNN_RL/main_AMP.py#L32).

**Comment by Fican1** [comment]
> Hi guys, I tried to setup environment with docker; however, there seems missing a .whl file: torch-1.13.1+cpu-cp310-cp310-linux_x86_64.whl.
Hi there! The `torch-1.13.1+cpu` file is quite large, so you'll need to download it manually from this link: [PyTorch 1.13.1 Files](https://pypi.org/project/torch/1.13.1/#files).

**Comment by Fican1** [comment]
> Hi guys, I tried to setup environment with docker; however, there seems missing a .whl file: torch-1.13.1+cpu-cp310-cp310-linux_x86_64.whl.

Hi there! The `torch-1.13.1+cpu` file is quite large, so you'll need to download it manually from this link: [PyTorch 1.13.1 Files](https://pypi.org/project/torch/1.13.1/#files).
